Fix broken GH Actions build
Error message:

```
Run hugo --minify -d ./public --baseURL https://mitjamartini.com/
WARN  Module "blowfish" is not compatible with this Hugo version: 0.141.0/0.148.2 extended; run "hugo mod graph" for more information.
Start building sites …
hugo v0.140.2-aae02ca612a02e085c08366a9c9279f4abb39d94+extended linux/amd64 BuildDate=2024-12-30T15:01:53Z VendorInfo=gohugoio

Total in 40 ms
Error: error building site: "/home/runner/work/mitja.github.io/mitja.github.io/themes/blowfish/layouts/shortcodes/codeberg.html:5:1": parse failed: template: shortcodes/codeberg.html:5: function "try" not defined
```

- Updated to latest actions-hugo (v3) (https://github.com/peaceiris/actions-hugo)
- Updated to latest hugo (v0.149.1) - https://github.com/gohugoio/hugo/releases

My local version is hugo v0.147.9+extended, and it works.

If time permits, I should look into nektos act (https://github.com/nektos/act) for testing GH actions, locally.